#############################################################################
# Makefile for building: pyramid-point-renderer
# Generated by qmake (2.01a) (Qt 4.3.2) on: Thu Jan 17 12:55:23 2008
# Project:  pyramid-point-renderer.pro
# Template: app
# Command: /usr/lib64/qt4/bin/qmake-qt4 -unix -o Makefile pyramid-point-renderer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtGui -I/usr/include/QtOpenGL -I/usr/include/QtOpenGL -I/usr/include -I. -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/X11R6/lib64 -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib64/qt4/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = application.cc \
		camera.cc \
		ewa_surface_splatting.cc \
		GLee.cpp \
		glslkernel.cc \
		interface.cc \
		interface.cpp \
		main.cpp \
		modelsTreeWidget.cpp \
		object.cc \
		ply.c \
		point_based_render.cc \
		pprMainWindow.cpp \
		primitives.cc \
		pyramid_point_render.cc \
		pyramid_point_render_color.cc \
		pyramid_point_render_trees.cc \
		pyramid_triangle_renderer.cc \
		surfels.cc \
		timer.c \
		triangle_renderer.cc moc_pprMainWindow.cpp
OBJECTS       = application.o \
		camera.o \
		ewa_surface_splatting.o \
		GLee.o \
		glslkernel.o \
		interface.o \
		interface.o \
		main.o \
		modelsTreeWidget.o \
		object.o \
		ply.o \
		point_based_render.o \
		pprMainWindow.o \
		primitives.o \
		pyramid_point_render.o \
		pyramid_point_render_color.o \
		pyramid_point_render_trees.o \
		pyramid_triangle_renderer.o \
		surfels.o \
		timer.o \
		triangle_renderer.o \
		moc_pprMainWindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++-multilib.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		pyramid-point-renderer.pro
QMAKE_TARGET  = pyramid-point-renderer
DESTDIR       = 
TARGET        = pyramid-point-renderer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_interface.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pyramid-point-renderer.pro  /usr/lib64/qt4/mkspecs/linux-g++-64/qmake.conf /usr/lib64/qt4/mkspecs/common/g++-multilib.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile pyramid-point-renderer.pro
/usr/lib64/qt4/mkspecs/common/g++-multilib.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile pyramid-point-renderer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/pyramid-point-renderer1.0.0 || $(MKDIR) .tmp/pyramid-point-renderer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/pyramid-point-renderer1.0.0/ && $(COPY_FILE) --parents application.h camera.h ewa_surface_splatting.h file_io.h GLee.h glslkernel.h interface.h materials.h modelsTreeWidget.h object.h openGLWidget.h ply.h point_based_render.h point_render.h pprMainWindow.h primitives.h pyramid_point_render.h pyramid_point_render_color.h pyramid_point_render_trees.h pyramid_triangle_renderer.h pyramid_types.h quat.h surfels.h timer.h triangle_renderer.h matrix.cc .tmp/pyramid-point-renderer1.0.0/ && $(COPY_FILE) --parents application.cc camera.cc ewa_surface_splatting.cc GLee.cpp glslkernel.cc interface.cc interface.cpp main.cpp modelsTreeWidget.cpp object.cc ply.c point_based_render.cc pprMainWindow.cpp primitives.cc pyramid_point_render.cc pyramid_point_render_color.cc pyramid_point_render_trees.cc pyramid_triangle_renderer.cc surfels.cc timer.c triangle_renderer.cc .tmp/pyramid-point-renderer1.0.0/ && $(COPY_FILE) --parents interface.ui .tmp/pyramid-point-renderer1.0.0/ && (cd `dirname .tmp/pyramid-point-renderer1.0.0` && $(TAR) pyramid-point-renderer1.0.0.tar pyramid-point-renderer1.0.0 && $(COMPRESS) pyramid-point-renderer1.0.0.tar) && $(MOVE) `dirname .tmp/pyramid-point-renderer1.0.0`/pyramid-point-renderer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/pyramid-point-renderer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


/usr/lib64/qt4/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_pprMainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_pprMainWindow.cpp
moc_pprMainWindow.cpp: ui_interface.h \
		modelsTreeWidget.h \
		application.h \
		camera.h \
		quat.h \
		materials.h \
		pyramid_point_render.h \
		timer.h \
		point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		object.h \
		primitives.h \
		pyramid_point_render_color.h \
		pyramid_point_render_trees.h \
		openGLWidget.h \
		pprMainWindow.h \
		/usr/lib64/qt4/bin/moc
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) pprMainWindow.h -o moc_pprMainWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_interface.h
compiler_uic_clean:
	-$(DEL_FILE) ui_interface.h
ui_interface.h: interface.ui \
		openGLWidget.h \
		modelsTreeWidget.h \
		application.h \
		camera.h \
		quat.h \
		materials.h \
		pyramid_point_render.h \
		timer.h \
		point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		object.h \
		primitives.h \
		pyramid_point_render_color.h \
		pyramid_point_render_trees.h \
		application.h \
		camera.h \
		quat.h \
		materials.h \
		pyramid_point_render.h \
		timer.h \
		point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		object.h \
		primitives.h \
		pyramid_point_render_color.h \
		pyramid_point_render_trees.h
	/usr/lib64/qt4/bin/uic interface.ui -o ui_interface.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

application.o: application.cc file_io.h \
		application.h \
		camera.h \
		quat.h \
		materials.h \
		pyramid_point_render.h \
		timer.h \
		point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		object.h \
		primitives.h \
		pyramid_point_render_color.h \
		pyramid_point_render_trees.h \
		ply.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o application.o application.cc

camera.o: camera.cc camera.h \
		quat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cc

ewa_surface_splatting.o: ewa_surface_splatting.cc ewa_surface_splatting.h \
		point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		materials.h \
		object.h \
		primitives.h \
		quat.h \
		matrix.cc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ewa_surface_splatting.o ewa_surface_splatting.cc

GLee.o: GLee.cpp GLee.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLee.o GLee.cpp

glslkernel.o: glslkernel.cc GLee.h \
		glslkernel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glslkernel.o glslkernel.cc

interface.o: interface.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interface.o interface.cc

interface.o: interface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interface.o interface.cpp

main.o: main.cpp ui_interface.h \
		modelsTreeWidget.h \
		application.h \
		camera.h \
		quat.h \
		materials.h \
		pyramid_point_render.h \
		timer.h \
		point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		object.h \
		primitives.h \
		pyramid_point_render_color.h \
		pyramid_point_render_trees.h \
		openGLWidget.h \
		pprMainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

modelsTreeWidget.o: modelsTreeWidget.cpp modelsTreeWidget.h \
		application.h \
		camera.h \
		quat.h \
		materials.h \
		pyramid_point_render.h \
		timer.h \
		point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		object.h \
		primitives.h \
		pyramid_point_render_color.h \
		pyramid_point_render_trees.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modelsTreeWidget.o modelsTreeWidget.cpp

object.o: object.cc object.h \
		primitives.h \
		surfels.h \
		quat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object.o object.cc

ply.o: ply.c ply.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ply.o ply.c

point_based_render.o: point_based_render.cc point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		materials.h \
		object.h \
		primitives.h \
		quat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point_based_render.o point_based_render.cc

pprMainWindow.o: pprMainWindow.cpp pprMainWindow.h \
		ui_interface.h \
		modelsTreeWidget.h \
		application.h \
		camera.h \
		quat.h \
		materials.h \
		pyramid_point_render.h \
		timer.h \
		point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		object.h \
		primitives.h \
		pyramid_point_render_color.h \
		pyramid_point_render_trees.h \
		openGLWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pprMainWindow.o pprMainWindow.cpp

primitives.o: primitives.cc primitives.h \
		surfels.h \
		quat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o primitives.o primitives.cc

pyramid_point_render.o: pyramid_point_render.cc pyramid_point_render.h \
		timer.h \
		point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		materials.h \
		object.h \
		primitives.h \
		quat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pyramid_point_render.o pyramid_point_render.cc

pyramid_point_render_color.o: pyramid_point_render_color.cc pyramid_point_render_color.h \
		timer.h \
		point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		materials.h \
		object.h \
		primitives.h \
		quat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pyramid_point_render_color.o pyramid_point_render_color.cc

pyramid_point_render_trees.o: pyramid_point_render_trees.cc pyramid_point_render_trees.h \
		timer.h \
		point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		materials.h \
		object.h \
		primitives.h \
		quat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pyramid_point_render_trees.o pyramid_point_render_trees.cc

pyramid_triangle_renderer.o: pyramid_triangle_renderer.cc pyramid_triangle_renderer.h \
		timer.h \
		point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		materials.h \
		object.h \
		primitives.h \
		quat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pyramid_triangle_renderer.o pyramid_triangle_renderer.cc

surfels.o: surfels.cc surfels.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o surfels.o surfels.cc

timer.o: timer.c timer.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o timer.o timer.c

triangle_renderer.o: triangle_renderer.cc triangle_renderer.h \
		point_based_render.h \
		glslkernel.h \
		surfels.h \
		pyramid_types.h \
		materials.h \
		object.h \
		primitives.h \
		quat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o triangle_renderer.o triangle_renderer.cc

moc_pprMainWindow.o: moc_pprMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pprMainWindow.o moc_pprMainWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

